# Token Test

In [2]:
from dagster_acled.acled_request_config import * 
from dagster_acled.secrets_config import *
import os
import polars as pl

sm = SecretManager(region_name=os.environ['REGION_NAME'])
client = AcledClientConfig()
token = await client.get_oauth_manager().get_access_token()

username = client.get_oauth_manager().username
password = client.get_oauth_manager().password

def mprint(df: pl.DataFrame) -> None: 
    with pl.Config(tbl_rows=df.shape[0], tbl_cols=df.shape[1]): 
        print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'dagster_pipeline/dagster_acled/resources/resource_config.yaml'

In [27]:
async def test_token(username: str, password: str, date: str):
    """Minimal test: get token, make API call."""
    
    # Get token
    data = aiohttp.FormData()
    data.add_field('username', username)
    data.add_field('password', password)
    data.add_field('grant_type', 'password')
    data.add_field('client_id', 'acled')
    
    async with aiohttp.ClientSession() as session:
        # Get token
        async with session.post('https://acleddata.com/oauth/token', data=data) as resp:
            token = (await resp.json())['access_token']
            print(f"Token: {token[:20]}...")
        
        headers = {'Authorization': f'Bearer {token}'}
        async with session.get(f'https://acleddata.com/api/acled/read?limit=5000&region=1&event_date={date}', headers=headers) as resp:
            data = await resp.json()
            return data

In [28]:
import asyncio
import polars as pl

data = await test_token(username, password, date = '2025-09-01')
df = pl.DataFrame(data['data'])

with pl.Config(tbl_rows=df.shape[0], tbl_cols=df.shape[1]): 
    print(pl.DataFrame(df.collect_schema()))

Token: eyJ0eXAiOiJKV1QiLCJh...
shape: (1, 31)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ eve ┆ eve ┆ yea ┆ tim ┆ dis ┆ eve ┆ sub ┆ act ┆ ass ┆ int ┆ act ┆ ass ┆ int ┆ int ┆ civ ┆ iso ┆ reg ┆ cou ┆ adm ┆ adm ┆ adm ┆ loc ┆ lat ┆ lon ┆ geo ┆ sou ┆ sou ┆ not ┆ fat ┆ tag ┆ tim │
│ nt_ ┆ nt_ ┆ r   ┆ e_p ┆ ord ┆ nt_ ┆ _ev ┆ or1 ┆ oc_ ┆ er1 ┆ or2 ┆ oc_ ┆ er2 ┆ era ┆ ili ┆ --- ┆ ion ┆ ntr ┆ in1 ┆ in2 ┆ in3 ┆ ati ┆ itu ┆ git ┆ _pr ┆ rce ┆ rce ┆ es  ┆ ali ┆ s   ┆ est │
│ id_ ┆ dat ┆ --- ┆ rec ┆ er_ ┆ typ ┆ ent ┆ --- ┆ act ┆ --- ┆ --- ┆ act ┆ --- ┆ cti ┆ an_ ┆ obj ┆ --- ┆ y   ┆ --- ┆ --- ┆ --- ┆ on  ┆ de  ┆ ude ┆ eci ┆ --- ┆ _sc ┆ --- ┆ tie ┆ --- ┆ amp │
│ cnt ┆ e   ┆ obj ┆ isi ┆ typ ┆ e   ┆ _ty ┆ obj ┆ or_ ┆ obj ┆ obj ┆ or_ ┆ obj ┆ on  ┆ tar ┆ ect ┆ obj ┆ --- ┆ obj ┆ obj ┆ obj ┆ --- ┆ --- ┆ --- ┆ sio ┆ obj ┆ ale ┆ obj ┆ s   ┆ obj ┆ --- │
│ y   ┆ --- ┆ ect ┆ on  ┆ e   ┆ --- ┆ pe  ┆ ect ┆ 1   ┆ ect ┆ ect ┆ 2   ┆ ect ┆ --- ┆ get ┆     ┆ ect ┆ obj ┆ ect ┆ ect ┆ ect ┆ obj ┆ obj ┆ obj ┆ n   ┆ ect ┆ --- ┆ ect ┆ --- ┆ ect ┆ obj │
│ --- ┆ obj ┆     ┆ --- ┆ --- ┆ obj ┆ --- ┆     ┆ --- ┆     ┆     ┆ --- ┆     ┆ obj ┆ ing ┆     ┆     ┆ ect ┆     ┆     ┆     ┆ ect ┆ ect ┆ ect ┆ --- ┆     ┆ obj ┆     ┆ obj ┆     ┆ ect │
│ obj ┆ ect ┆     ┆ obj ┆ obj ┆ ect ┆ obj ┆     ┆ obj ┆     ┆     ┆ obj ┆     ┆ ect ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ obj ┆     ┆ ect ┆     ┆ ect ┆     ┆     │
│ ect ┆     ┆     ┆ ect ┆ ect ┆     ┆ ect ┆     ┆ ect ┆     ┆     ┆ ect ┆     ┆     ┆ obj ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ Str ┆ Str ┆ Int ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Int ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Int ┆ Str ┆ Str ┆ Str ┆ Int ┆ Str ┆ Int │
│ ing ┆ ing ┆ 64  ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ 64  ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ 64  ┆ ing ┆ ing ┆ ing ┆ 64  ┆ ing ┆ 64  │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [38]:
actors = df.select('actor1').unique()

In [ ]:


async def test_cookie_auth(username: str, password: str):
    """Minimal test: login with cookies, make API call."""
    
    async with aiohttp.ClientSession() as session:
        login_data = {
            "name": username,
            "pass": password
        }
        
        async with session.post(
            'https://acleddata.com/user/login?_format=json',
            json=login_data,
            headers={'Content-Type': 'application/json'}
        ) as login_resp:
            login_result = await login_resp.json()
            print(f"Login response: {login_result}")
            print(f"Cookies after login: {len(session.cookie_jar)} cookies")
        
        async with session.get(
            'https://acleddata.com/api/acled/read?limit=1&event_date=2024-12-31'
        ) as api_resp:
            data = await api_resp.json()
            print(f"API response status: {api_resp.status}")
            return data

result = await test_cookie_auth(username=username,password=password)
print(result)

Login response: {'current_user': {'uid': '59469', 'name': 's.a.bojilov@umail.leidenuniv.nl'}, 'csrf_token': '3_d7dxkGreXNTYwht65QrU3SZFXGkjF0m0OwW5temUY', 'logout_token': 'Vd3lt9wRVESord-vBM0uqWrkcoDD-BGI2UB6a6nhasQ'}
Cookies after login: 1 cookies
API response status: 200
{'status': 200, 'success': True, 'count': 0, 'total_count': 0, 'messages': [], 'data': [], 'filename': 'results.json', 'data_query_restrictions': {'countries': [], 'event_types': [], 'regions': [], 'history': [], 'recency': [], 'date_recency': {'quantity': 12, 'unit': 'Months', 'description': '12 Months old', 'timestamp': 1726586733, 'date': '2024-09-17'}}}

# Load datalake

In [6]:
import yaml

with open('/Users/stefanbozhilov/repos/acled/acled/dagster_pipeline/dagster_acled/resources/resource_config.yaml', 'r') as file:
    config = yaml.safe_load(file)

from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient

# No credentials in code!
credential = DefaultAzureCredential(exclude_managed_identity_credential=True)
blob_service_client = BlobServiceClient(
    account_url=config['storage_account']['url'],
    credential=credential
)

container_client = blob_service_client.get_container_client("acled-container")
token = credential.get_token("https://storage.azure.com/.default")

# Pass the token to Polars
credential_provider = {
    "account_name": f"{config['storage_account']['name']}",
    "bearer_token": token.token
}

In [12]:
from dagster_acled.resources.resources import ResourceConfig
import polars as pl

resource_dict = ResourceConfig.load_resource_config()
container = resource_dict['storage_account']['container']
account_name = resource_dict['storage_account']['name']

# Read without any casting
df = pl.scan_parquet(
    f"az://{container}/daily_data/africa/**/*.parquet",
    storage_options={'account_name': account_name},
    credential_provider=ResourceConfig.blob_credential_provider, 
    extra_columns='ignore',
    cast_options=pl.ScanCastOptions(integer_cast='upcast')
)

# Filter for JNIM events
jnim_pattern = r"(?i)jnim|jama'?at nusrat|nusrat al-islam"

jnim_df = df.filter(
    pl.any_horizontal(
        pl.col("actor1", "actor2", "assoc_actor_1", "assoc_actor_2")
          .fill_null("")
          .str.contains(jnim_pattern, literal=False)
    )
)

result = jnim_df.collect(engine='streaming')

print(f'Shape:{result.shape}')

Shape:(15582, 30)

In [23]:
df = pl.scan_parquet(
    f"az://{container}/consolidated/jnim_events.parquet",
    storage_options={'account_name': account_name},
    credential_provider=ResourceConfig.blob_credential_provider, 
    extra_columns='ignore',
    cast_options=pl.ScanCastOptions(integer_cast='upcast')
).collect()

In [21]:
actors = (
    result
    .select(
        pl.concat_list("actor1")
        .list.explode()
        .drop_nulls()
        .unique()
        .alias("actor")
    )
)

In [22]:
actors

shape: (72, 1)
┌─────────────────────────────────┐
│ actor                           │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Bambara Ethnic Militia (Mali)   │
│ Unidentified Armed Group (Burk… │
│ Wagner Group                    │
│ Military Forces of Mali (2020-… │
│ JNIM: Group for Support of Isl… │
│ …                               │
│ Police Forces of Mali (2021-) … │
│ Police Forces of Benin (2016-)  │
│ CMA: Coordination of Movements… │
│ MINUSMA: United Nations Multid… │
│ Military Forces of Burkina Fas… │
└─────────────────────────────────┘

In [5]:
from dagster_acled.resources.resources import ResourceConfig
import polars as pl
from azure.storage.blob import ContainerClient
from pathlib import Path
from tqdm import tqdm


resource_dict = ResourceConfig.load_resource_config()
container = resource_dict['storage_account']['container']
account_name = resource_dict['storage_account']['name']

# Get blob service client
from azure.identity import DefaultAzureCredential
credential = DefaultAzureCredential()
container_client = ContainerClient(
    account_url=f"https://{account_name}.blob.core.windows.net",
    container_name=container,
    credential=credential
)

# List all parquet files
print("Scanning for parquet files...")
blobs = container_client.list_blobs(name_starts_with="daily_data/africa/")
parquet_files = [blob.name for blob in blobs if blob.name.endswith('.parquet')]

print(f"Found {len(parquet_files)} parquet files")
parquet_files = parquet_files[3490:]

Scanning for parquet files...
Found 3591 parquet files

In [6]:
# Check and fix each file
files_to_fix = []
files_fixed = []

for blob_name in tqdm(parquet_files, desc='Processing files', unit ='file'):
    try:
        # Read the file
        file_path = f"az://{container}/{blob_name}"
        df = pl.read_parquet(
            file_path,
            storage_options={'account_name': account_name},
            credential_provider=ResourceConfig.blob_credential_provider,
        )
        
        # Check if event_date is String
        if df.schema['event_date'] == pl.Utf8 or df.schema['event_date'] == pl.String:
            print(f"Found String event_date: {blob_name}")
            files_to_fix.append(blob_name)
            
            # Fix it: cast to Date
            df_fixed = df.with_columns([
                pl.col("event_date").str.strptime(pl.Date, "%Y-%m-%d", strict=False),
                pl.col("year").cast(pl.Int16, strict=False),
                pl.col("time_precision").cast(pl.Int16, strict=False),
                pl.col("iso").cast(pl.Int16, strict=False),
                pl.col("geo_precision").cast(pl.Int16, strict=False),
                pl.col("fatalities").cast(pl.Int16, strict=False),
                pl.col("latitude").cast(pl.Float64, strict=False),
                pl.col("longitude").cast(pl.Float64, strict=False),
                pl.col("timestamp").cast(pl.Int64).cast(pl.Datetime("ms"), strict=False),
                ])
            
            # Write back
            df_fixed.write_parquet(
                file_path,
                storage_options={'account_name': account_name},
                credential_provider=ResourceConfig.blob_credential_provider,
            )
            
            files_fixed.append(blob_name)
            print(f"  ✓ Fixed {blob_name}")
            
    except Exception as e:
        print(f"  ✗ Error processing {blob_name}: {e}")

print(f"\n{'='*60}")
print(f"Summary:")
print(f"  Total files scanned: {len(parquet_files)}")
print(f"  Files needing fix: {len(files_to_fix)}")
print(f"  Files fixed: {len(files_fixed)}")
print(f"{'='*60}")

if files_fixed:
    print("\nFixed files:")
    for f in files_fixed:
        print(f"  - {f}")

Processing files:  97%|█████████▋| 98/101 [01:39<00:02,  1.12file/s]

Found String event_date: daily_data/africa/event_date=2025-11-05/0.parquet

Processing files:  98%|█████████▊| 99/101 [01:40<00:02,  1.11s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-05/0.parquet
Found String event_date: daily_data/africa/event_date=2025-11-06/0.parquet

Processing files:  99%|█████████▉| 100/101 [01:42<00:01,  1.26s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-06/0.parquet
Found String event_date: daily_data/africa/event_date=2025-11-07/0.parquet

Processing files: 100%|██████████| 101/101 [01:44<00:00,  1.03s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-07/0.parquet

============================================================
Summary:
  Total files scanned: 101
  Files needing fix: 3
  Files fixed: 3
============================================================

Fixed files:
  - daily_data/africa/event_date=2025-11-05/0.parquet
  - daily_data/africa/event_date=2025-11-06/0.parquet
  - daily_data/africa/event_date=2025-11-07/0.parquet

In [24]:
target_files = [
    "daily_data/africa/event_date=2024-01-06/0.parquet",
    "daily_data/africa/event_date=2024-07-15/0.parquet",
    "daily_data/africa/event_date=2024-07-31/0.parquet",
    "daily_data/africa/event_date=2024-10-23/0.parquet",
    "daily_data/africa/event_date=2025-02-10/0.parquet",
    "daily_data/africa/event_date=2025-02-11/0.parquet",
    "daily_data/africa/event_date=2025-02-12/0.parquet",
    "daily_data/africa/event_date=2025-02-13/0.parquet",
    "daily_data/africa/event_date=2025-02-14/0.parquet",
    "daily_data/africa/event_date=2025-02-15/0.parquet",
    "daily_data/africa/event_date=2025-02-16/0.parquet",
    "daily_data/africa/event_date=2025-09-24/0.parquet",
    "daily_data/africa/event_date=2025-09-27/0.parquet",
    "daily_data/africa/event_date=2025-09-28/0.parquet",
    "daily_data/africa/event_date=2025-09-29/0.parquet",
    "daily_data/africa/event_date=2025-09-30/0.parquet",
    "daily_data/africa/event_date=2025-10-01/0.parquet",
    "daily_data/africa/event_date=2025-10-02/0.parquet",
    "daily_data/africa/event_date=2025-10-03/0.parquet",
    "daily_data/africa/event_date=2025-10-04/0.parquet",
    "daily_data/africa/event_date=2025-10-05/0.parquet",
    "daily_data/africa/event_date=2025-10-06/0.parquet",
    "daily_data/africa/event_date=2025-10-07/0.parquet",
    "daily_data/africa/event_date=2025-10-16/0.parquet",
    "daily_data/africa/event_date=2025-10-17/0.parquet",
    "daily_data/africa/event_date=2025-10-18/0.parquet",
    "daily_data/africa/event_date=2025-10-19/0.parquet",
    "daily_data/africa/event_date=2025-10-20/0.parquet",
    "daily_data/africa/event_date=2025-10-21/0.parquet",
    "daily_data/africa/event_date=2025-10-22/0.parquet",
    "daily_data/africa/event_date=2025-10-23/0.parquet",
    "daily_data/africa/event_date=2025-10-24/0.parquet",
    "daily_data/africa/event_date=2025-10-26/0.parquet",
    "daily_data/africa/event_date=2025-10-27/0.parquet",
    "daily_data/africa/event_date=2025-10-28/0.parquet",
    "daily_data/africa/event_date=2025-10-29/0.parquet",
    "daily_data/africa/event_date=2025-10-30/0.parquet",
    "daily_data/africa/event_date=2025-10-31/0.parquet",
    "daily_data/africa/event_date=2025-11-01/0.parquet",
    "daily_data/africa/event_date=2025-11-02/0.parquet",
    "daily_data/africa/event_date=2025-11-03/0.parquet",
    "daily_data/africa/event_date=2025-11-04/0.parquet",
    "daily_data/africa/event_date=2025-11-05/0.parquet",
    "daily_data/africa/event_date=2025-11-06/0.parquet",
    "daily_data/africa/event_date=2025-11-07/0.parquet",
]
target_files[-1]

'daily_data/africa/event_date=2025-11-07/0.parquet'

In [ ]:
from dagster_acled.resources.resources import ResourceConfig
import polars as pl
from azure.storage.blob import ContainerClient
from pathlib import Path
from tqdm import tqdm


resource_dict = ResourceConfig.load_resource_config()
container = resource_dict['storage_account']['container']
account_name = resource_dict['storage_account']['name']

# Get blob service client
from azure.identity import DefaultAzureCredential
credential = DefaultAzureCredential()
container_client = ContainerClient(
    account_url=f"https://{account_name}.blob.core.windows.net",
    container_name=container,
    credential=credential
)

# Specific files to process
target_files = [
    "daily_data/africa/event_date=2024-01-06/0.parquet",
    "daily_data/africa/event_date=2024-07-15/0.parquet",
    "daily_data/africa/event_date=2024-07-31/0.parquet",
    "daily_data/africa/event_date=2024-10-23/0.parquet",
    "daily_data/africa/event_date=2025-02-10/0.parquet",
    "daily_data/africa/event_date=2025-02-11/0.parquet",
    "daily_data/africa/event_date=2025-02-12/0.parquet",
    "daily_data/africa/event_date=2025-02-13/0.parquet",
    "daily_data/africa/event_date=2025-02-14/0.parquet",
    "daily_data/africa/event_date=2025-02-15/0.parquet",
    "daily_data/africa/event_date=2025-02-16/0.parquet",
    "daily_data/africa/event_date=2025-09-24/0.parquet",
    "daily_data/africa/event_date=2025-09-27/0.parquet",
    "daily_data/africa/event_date=2025-09-28/0.parquet",
    "daily_data/africa/event_date=2025-09-29/0.parquet",
    "daily_data/africa/event_date=2025-09-30/0.parquet",
    "daily_data/africa/event_date=2025-10-01/0.parquet",
    "daily_data/africa/event_date=2025-10-02/0.parquet",
    "daily_data/africa/event_date=2025-10-03/0.parquet",
    "daily_data/africa/event_date=2025-10-04/0.parquet",
    "daily_data/africa/event_date=2025-10-05/0.parquet",
    "daily_data/africa/event_date=2025-10-06/0.parquet",
    "daily_data/africa/event_date=2025-10-07/0.parquet",
    "daily_data/africa/event_date=2025-10-16/0.parquet",
    "daily_data/africa/event_date=2025-10-17/0.parquet",
    "daily_data/africa/event_date=2025-10-18/0.parquet",
    "daily_data/africa/event_date=2025-10-19/0.parquet",
    "daily_data/africa/event_date=2025-10-20/0.parquet",
    "daily_data/africa/event_date=2025-10-21/0.parquet",
    "daily_data/africa/event_date=2025-10-22/0.parquet",
    "daily_data/africa/event_date=2025-10-23/0.parquet",
    "daily_data/africa/event_date=2025-10-24/0.parquet",
    "daily_data/africa/event_date=2025-10-26/0.parquet",
    "daily_data/africa/event_date=2025-10-27/0.parquet",
    "daily_data/africa/event_date=2025-10-28/0.parquet",
    "daily_data/africa/event_date=2025-10-29/0.parquet",
    "daily_data/africa/event_date=2025-10-30/0.parquet",
    "daily_data/africa/event_date=2025-10-31/0.parquet",
    "daily_data/africa/event_date=2025-11-01/0.parquet",
    "daily_data/africa/event_date=2025-11-02/0.parquet",
    "daily_data/africa/event_date=2025-11-03/0.parquet",
    "daily_data/africa/event_date=2025-11-04/0.parquet",
    "daily_data/africa/event_date=2025-11-05/0.parquet",
    "daily_data/africa/event_date=2025-11-06/0.parquet",
    "daily_data/africa/event_date=2025-11-07/0.parquet",
]

print(f"Processing {len(target_files)} specific files")

# Check and fix each file
files_fixed = []
files_errored = []

for blob_name in tqdm(target_files[-1], desc='Processing files', unit='file'):
    try:
        # Read the file
        file_path = f"az://{container}/{blob_name}"
        df = pl.read_parquet(
            file_path,
            storage_options={'account_name': account_name},
            credential_provider=ResourceConfig.blob_credential_provider,
        )
        
        # Build schema enforcement with proper handling
        cast_expressions = []
        
        # Handle event_date - convert String to Date
        if df.schema['event_date'] in (pl.Utf8, pl.String):
            cast_expressions.append(
                pl.col("event_date").str.strptime(pl.Date, "%Y-%m-%d", strict=False)
            )
        elif df.schema['event_date'] != pl.Date:
            cast_expressions.append(pl.col("event_date").cast(pl.Date, strict=False))
        
        # Enforce integer types
        if 'year' in df.columns:
            cast_expressions.append(pl.col("year").cast(pl.Int16, strict=False))
        if 'time_precision' in df.columns:
            cast_expressions.append(pl.col("time_precision").cast(pl.Int16, strict=False))
        if 'iso' in df.columns:
            cast_expressions.append(pl.col("iso").cast(pl.Int16, strict=False))
        if 'geo_precision' in df.columns:
            cast_expressions.append(pl.col("geo_precision").cast(pl.Int16, strict=False))
        if 'fatalities' in df.columns:
            cast_expressions.append(pl.col("fatalities").cast(pl.Int16, strict=False))
        
        # Enforce float types
        if 'latitude' in df.columns:
            cast_expressions.append(pl.col("latitude").cast(pl.Float64, strict=False))
        if 'longitude' in df.columns:
            cast_expressions.append(pl.col("longitude").cast(pl.Float64, strict=False))
        
        # Handle timestamp - convert to datetime if it's Int64
        if 'timestamp' in df.columns:
            if df.schema['timestamp'] == pl.Int64:
                cast_expressions.append(
                    pl.col("timestamp").cast(pl.Datetime("ms"), strict=False)
                )
            elif df.schema['timestamp'] != pl.Datetime("ms"):
                cast_expressions.append(
                    pl.col("timestamp").cast(pl.Datetime("ms"), strict=False)
                )
        
        # Apply all casts if needed
        if cast_expressions:
            df_fixed = df.with_columns(cast_expressions)
            
            # Write back
            df_fixed.write_parquet(
                file_path,
                storage_options={'account_name': account_name},
                credential_provider=ResourceConfig.blob_credential_provider,
            )
            
            files_fixed.append(blob_name)
            print(f"  ✓ Fixed {blob_name}")
        else:
            print(f"  → No changes needed for {blob_name}")
            
    except Exception as e:
        print(f"  ✗ Error processing {blob_name}: {e}")
        files_errored.append((blob_name, str(e)))

print(f"\n{'='*60}")
print(f"Summary:")
print(f"  Total files processed: {len(target_files)}")
print(f"  Files fixed: {len(files_fixed)}")
print(f"  Files with errors: {len(files_errored)}")
print(f"{'='*60}")

if files_fixed:
    print("\nFixed files:")
    for f in files_fixed:
        print(f"  - {f}")

if files_errored:
    print("\nFiles with errors:")
    for f, err in files_errored:
        print(f"  - {f}: {err}")

Processing 45 specific files

Processing files:   0%|          | 0/49 [00:00<?, ?file/s]

Processing files:   2%|▏         | 1/49 [00:03<03:02,  3.80s/file]

  ✗ Error processing d: object-store error: Object at location d not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/d in 167.923916ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

Processing files:   4%|▍         | 2/49 [00:06<02:22,  3.03s/file]

  ✗ Error processing a: object-store error: Object at location a not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/a in 162.157459ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

Processing files:   6%|▌         | 3/49 [00:07<01:44,  2.27s/file]

  ✗ Error processing i: object-store error: Object at location i not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/i in 152.767625ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

Processing files:   8%|▊         | 4/49 [00:09<01:27,  1.95s/file]

  ✗ Error processing l: object-store error: Object at location l not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/l in 154.713167ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

Processing files:  10%|█         | 5/49 [00:10<01:16,  1.75s/file]

  ✗ Error processing y: object-store error: Object at location y not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/y in 148.931459ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

Processing files:  12%|█▏        | 6/49 [00:11<01:09,  1.62s/file]

  ✗ Error processing _: object-store error: Object at location _ not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/_ in 147.905959ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

Processing files:  14%|█▍        | 7/49 [00:13<01:06,  1.58s/file]

  ✗ Error processing d: object-store error: Object at location d not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/d in 143.367709ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

Processing files:  16%|█▋        | 8/49 [00:14<01:04,  1.57s/file]

  ✗ Error processing a: object-store error: Object at location a not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/a in 220.009833ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

Processing files:  18%|█▊        | 9/49 [00:16<01:03,  1.60s/file]

  ✗ Error processing t: object-store error: Object at location t not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/t in 217.040042ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

Processing files:  20%|██        | 10/49 [00:18<01:03,  1.62s/file]

  ✗ Error processing a: object-store error: Object at location a not found: Error performing HEAD https://acledbucket.blob.core.windows.net/acled-container/a in 281.812291ms - Server returned non-2xx status code: 404 Not Found: ; note: if you are using Python, consider setting POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1 if you would like polars to try to retrieve and use the storage account keys from Azure CLI to authenticate

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

In [ ]:
import polars as pl


result = (
    pl.scan_parquet("s3://dagster-acled-bucket/acled/acled_daily_data/acled_africa/*")
    .select([pl.exclude("tags")])
    .sort("event_type")
    .collect(engine="streaming")
    .limit(n = 100)
)

In [7]:
result.select('event_date').max()

shape: (1, 1)
┌────────────┐
│ event_date │
│ ---        │
│ date       │
╞════════════╡
│ 2016-01-08 │
└────────────┘

In [1]:
import yaml
import polars as pl
from azure.identity import DefaultAzureCredential

with open('/Users/stefanbozhilov/repos/acled/acled/dagster_pipeline/dagster_acled/resources/resource_config.yaml', 'r') as file:
    config = yaml.safe_load(file)

credential = DefaultAzureCredential()
token = credential.get_token("https://storage.azure.com/.default")

# Correct parameter name and format
storage_options = {
    "account_name": config['storage_account']['name'],
    "bearer_token": token.token
}

# result.write_parquet(
#     file=f"az://{config['storage_account']['container']}/daily_data/africa",
#     storage_options=storage_options,  # Changed from credential_provider
#     partition_by=['event_date']
# )

In [24]:
import os
from dagster import Definitions, asset, EnvVar
from dagster_azure.blob import (
    AzureBlobStorageResource,
    AzureBlobStorageKeyCredential,
    AzureBlobStorageDefaultCredential
)

@asset
def my_table(azure_blob_storage: AzureBlobStorageResource):
    with azure_blob_storage.get_client() as blob_storage_client:
        response = blob_storage_client.list_containers()

definitions = Definitions(
    assets=[my_table],
    resources={
        "azure_blob_storage": AzureBlobStorageResource(
            account_url=config['storage_account']['url'],
            credential = AzureBlobStorageDefaultCredential()
        ),
    },
)

In [ ]:
import os

from dagster import (
    Definitions,
    load_asset_checks_from_modules,
    load_assets_from_modules,
    multiprocess_executor,
)
from dotenv import load_dotenv

from dagster_acled.asset_checks import acled_checks
from dagster_acled.assets import base_assets, ml, report, country_assets
from dagster_acled.jobs import acled_update_job
from dagster_acled.utils import load_config
from dagster_acled.resources.io_manager import (
    reports_s3_io_manager,
    s3_io_manager,
    s3_pickle_io_manager,
)
from dagster_acled.resources.resources import ResourceConfig
from dagster_acled.schedules import daily_schedule
from dagster_acled.secrets_config import SecretManager
from dagster_acled.sensors import acled_sensor, s3_data_availability_sensor
from dagster_azure.blob import (
    AzureBlobStorageResource,
    AzureBlobStorageDefaultCredential
)

load_dotenv()

sm = SecretManager(region_name=os.environ['REGION_NAME'])
resource_config = ResourceConfig.from_secrets(sm=sm, s3_secret_name="acled_bucket", pg_secret_name="acled_postgres")
resource_yaml = load_config(config_path="dagster_pipeline/dagster_acled/resources/resource_config.yaml")

resources = {
    "s3": resource_config.s3,
    "postgres": resource_config.postgres,
    "s3_io_manager": s3_io_manager,
    "reports_s3_io_manager": reports_s3_io_manager,
    "s3_pickle_io_manager": s3_pickle_io_manager,
    "azure_blob_storage": AzureBlobStorageResource(
            account_url=(resource_yaml['storage_account']['url']),
            credential=AzureBlobStorageDefaultCredential()
    )
}

FileNotFoundError: [Errno 2] No such file or directory: 'dagster_acled/resources/resource_config.yaml'

In [9]:
from dagster_acled.secrets_config import *

In [1]:
from dagster_acled.acled_request_config import * 
from dagster_acled.secrets_config import *
import yaml

with open('/Users/stefanbozhilov/repos/acled/acled/dagster_pipeline/dagster_acled/resources/resource_config.yaml', 'r') as file:
    config = yaml.safe_load(file)

sm = SecretManager(vault_url = config['keyvault']['url'], 
                   region_name=None)   

cred = sm.get_secret(secret_name='acled-credentials', 
                     source = 'az')

username = cred['username']
password = cred['password']

/Users/stefanbozhilov/repos/acled/acled/dagster_pipeline/.venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:198: UserWarning: Field name "schema" in "PostgreSQLResource" shadows an attribute in parent "ConfigurableResource"
  warnings.warn(