# Token Test

In [2]:
from dagster_acled.acled_request_config import * 
from dagster_acled.secrets_config import *
import os
import polars as pl

sm = SecretManager(region_name=os.environ['REGION_NAME'])
client = AcledClientConfig()
token = await client.get_oauth_manager().get_access_token()

username = client.get_oauth_manager().username
password = client.get_oauth_manager().password

def mprint(df: pl.DataFrame) -> None: 
    with pl.Config(tbl_rows=df.shape[0], tbl_cols=df.shape[1]): 
        print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'dagster_pipeline/dagster_acled/resources/resource_config.yaml'

In [27]:
async def test_token(username: str, password: str, date: str):
    """Minimal test: get token, make API call."""
    
    # Get token
    data = aiohttp.FormData()
    data.add_field('username', username)
    data.add_field('password', password)
    data.add_field('grant_type', 'password')
    data.add_field('client_id', 'acled')
    
    async with aiohttp.ClientSession() as session:
        # Get token
        async with session.post('https://acleddata.com/oauth/token', data=data) as resp:
            token = (await resp.json())['access_token']
            print(f"Token: {token[:20]}...")
        
        headers = {'Authorization': f'Bearer {token}'}
        async with session.get(f'https://acleddata.com/api/acled/read?limit=5000&region=1&event_date={date}', headers=headers) as resp:
            data = await resp.json()
            return data

In [28]:
import asyncio
import polars as pl

data = await test_token(username, password, date = '2025-09-01')
df = pl.DataFrame(data['data'])

with pl.Config(tbl_rows=df.shape[0], tbl_cols=df.shape[1]): 
    print(pl.DataFrame(df.collect_schema()))

Token: eyJ0eXAiOiJKV1QiLCJh...
shape: (1, 31)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ eve ┆ eve ┆ yea ┆ tim ┆ dis ┆ eve ┆ sub ┆ act ┆ ass ┆ int ┆ act ┆ ass ┆ int ┆ int ┆ civ ┆ iso ┆ reg ┆ cou ┆ adm ┆ adm ┆ adm ┆ loc ┆ lat ┆ lon ┆ geo ┆ sou ┆ sou ┆ not ┆ fat ┆ tag ┆ tim │
│ nt_ ┆ nt_ ┆ r   ┆ e_p ┆ ord ┆ nt_ ┆ _ev ┆ or1 ┆ oc_ ┆ er1 ┆ or2 ┆ oc_ ┆ er2 ┆ era ┆ ili ┆ --- ┆ ion ┆ ntr ┆ in1 ┆ in2 ┆ in3 ┆ ati ┆ itu ┆ git ┆ _pr ┆ rce ┆ rce ┆ es  ┆ ali ┆ s   ┆ est │
│ id_ ┆ dat ┆ --- ┆ rec ┆ er_ ┆ typ ┆ ent ┆ --- ┆ act ┆ --- ┆ --- ┆ act ┆ --- ┆ cti ┆ an_ ┆ obj ┆ --- ┆ y   ┆ --- ┆ --- ┆ --- ┆ on  ┆ de  ┆ ude ┆ eci ┆ --- ┆ _sc ┆ --- ┆ tie ┆ --- ┆ amp │
│ cnt ┆ e   ┆ obj ┆ isi ┆ typ ┆ e   ┆ _ty ┆ obj ┆ or_ ┆ obj ┆ obj ┆ or_ ┆ obj ┆ on  ┆ tar ┆ ect ┆ obj ┆ --- ┆ obj ┆ obj ┆ obj ┆ --- ┆ --- ┆ --- ┆ sio ┆ obj ┆ ale ┆ obj ┆ s   ┆ obj ┆ --- │
│ y   ┆ --- ┆ ect ┆ on  ┆ e   ┆ --- ┆ pe  ┆ ect ┆ 1   ┆ ect ┆ ect ┆ 2   ┆ ect ┆ --- ┆ get ┆     ┆ ect ┆ obj ┆ ect ┆ ect ┆ ect ┆ obj ┆ obj ┆ obj ┆ n   ┆ ect ┆ --- ┆ ect ┆ --- ┆ ect ┆ obj │
│ --- ┆ obj ┆     ┆ --- ┆ --- ┆ obj ┆ --- ┆     ┆ --- ┆     ┆     ┆ --- ┆     ┆ obj ┆ ing ┆     ┆     ┆ ect ┆     ┆     ┆     ┆ ect ┆ ect ┆ ect ┆ --- ┆     ┆ obj ┆     ┆ obj ┆     ┆ ect │
│ obj ┆ ect ┆     ┆ obj ┆ obj ┆ ect ┆ obj ┆     ┆ obj ┆     ┆     ┆ obj ┆     ┆ ect ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ obj ┆     ┆ ect ┆     ┆ ect ┆     ┆     │
│ ect ┆     ┆     ┆ ect ┆ ect ┆     ┆ ect ┆     ┆ ect ┆     ┆     ┆ ect ┆     ┆     ┆ obj ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ Str ┆ Str ┆ Int ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Int ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Str ┆ Int ┆ Str ┆ Str ┆ Str ┆ Int ┆ Str ┆ Int │
│ ing ┆ ing ┆ 64  ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ 64  ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ ing ┆ 64  ┆ ing ┆ ing ┆ ing ┆ 64  ┆ ing ┆ 64  │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [38]:
actors = df.select('actor1').unique()

In [ ]:


async def test_cookie_auth(username: str, password: str):
    """Minimal test: login with cookies, make API call."""
    
    async with aiohttp.ClientSession() as session:
        login_data = {
            "name": username,
            "pass": password
        }
        
        async with session.post(
            'https://acleddata.com/user/login?_format=json',
            json=login_data,
            headers={'Content-Type': 'application/json'}
        ) as login_resp:
            login_result = await login_resp.json()
            print(f"Login response: {login_result}")
            print(f"Cookies after login: {len(session.cookie_jar)} cookies")
        
        async with session.get(
            'https://acleddata.com/api/acled/read?limit=1&event_date=2024-12-31'
        ) as api_resp:
            data = await api_resp.json()
            print(f"API response status: {api_resp.status}")
            return data

result = await test_cookie_auth(username=username,password=password)
print(result)

Login response: {'current_user': {'uid': '59469', 'name': 's.a.bojilov@umail.leidenuniv.nl'}, 'csrf_token': '3_d7dxkGreXNTYwht65QrU3SZFXGkjF0m0OwW5temUY', 'logout_token': 'Vd3lt9wRVESord-vBM0uqWrkcoDD-BGI2UB6a6nhasQ'}
Cookies after login: 1 cookies
API response status: 200
{'status': 200, 'success': True, 'count': 0, 'total_count': 0, 'messages': [], 'data': [], 'filename': 'results.json', 'data_query_restrictions': {'countries': [], 'event_types': [], 'regions': [], 'history': [], 'recency': [], 'date_recency': {'quantity': 12, 'unit': 'Months', 'description': '12 Months old', 'timestamp': 1726586733, 'date': '2024-09-17'}}}

# Load datalake

In [6]:
import yaml

with open('/Users/stefanbozhilov/repos/acled/acled/dagster_pipeline/dagster_acled/resources/resource_config.yaml', 'r') as file:
    config = yaml.safe_load(file)

from azure.identity import DefaultAzureCredential
from azure.storage.blob import BlobServiceClient

# No credentials in code!
credential = DefaultAzureCredential(exclude_managed_identity_credential=True)
blob_service_client = BlobServiceClient(
    account_url=config['storage_account']['url'],
    credential=credential
)

container_client = blob_service_client.get_container_client("acled-container")
token = credential.get_token("https://storage.azure.com/.default")

# Pass the token to Polars
credential_provider = {
    "account_name": f"{config['storage_account']['name']}",
    "bearer_token": token.token
}

In [12]:
from dagster_acled.resources.resources import ResourceConfig
import polars as pl

resource_dict = ResourceConfig.load_resource_config()
container = resource_dict['storage_account']['container']
account_name = resource_dict['storage_account']['name']

# Read without any casting
df = pl.scan_parquet(
    f"az://{container}/daily_data/africa/**/*.parquet",
    storage_options={'account_name': account_name},
    credential_provider=ResourceConfig.blob_credential_provider, 
    extra_columns='ignore',
    cast_options=pl.ScanCastOptions(integer_cast='upcast')
)

# Filter for JNIM events
jnim_pattern = r"(?i)jnim|jama'?at nusrat|nusrat al-islam"

jnim_df = df.filter(
    pl.any_horizontal(
        pl.col("actor1", "actor2", "assoc_actor_1", "assoc_actor_2")
          .fill_null("")
          .str.contains(jnim_pattern, literal=False)
    )
)

result = jnim_df.collect(engine='streaming')

print(f'Shape:{result.shape}')

Shape:(15582, 30)

In [23]:
df = pl.scan_parquet(
    f"az://{container}/consolidated/jnim_events.parquet",
    storage_options={'account_name': account_name},
    credential_provider=ResourceConfig.blob_credential_provider, 
    extra_columns='ignore',
    cast_options=pl.ScanCastOptions(integer_cast='upcast')
).collect()

In [21]:
actors = (
    result
    .select(
        pl.concat_list("actor1")
        .list.explode()
        .drop_nulls()
        .unique()
        .alias("actor")
    )
)

In [22]:
actors

shape: (72, 1)
┌─────────────────────────────────┐
│ actor                           │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Bambara Ethnic Militia (Mali)   │
│ Unidentified Armed Group (Burk… │
│ Wagner Group                    │
│ Military Forces of Mali (2020-… │
│ JNIM: Group for Support of Isl… │
│ …                               │
│ Police Forces of Mali (2021-) … │
│ Police Forces of Benin (2016-)  │
│ CMA: Coordination of Movements… │
│ MINUSMA: United Nations Multid… │
│ Military Forces of Burkina Fas… │
└─────────────────────────────────┘

In [ ]:
from dagster_acled.resources.resources import ResourceConfig
import polars as pl
from azure.storage.blob import ContainerClient
from pathlib import Path
from tqdm import tqdm


resource_dict = ResourceConfig.load_resource_config()
container = resource_dict['storage_account']['container']
account_name = resource_dict['storage_account']['name']

# Get blob service client
from azure.identity import DefaultAzureCredential
credential = DefaultAzureCredential()
container_client = ContainerClient(
    account_url=f"https://{account_name}.blob.core.windows.net",
    container_name=container,
    credential=credential
)

# List all parquet files
print("Scanning for parquet files...")
blobs = container_client.list_blobs(name_starts_with="daily_data/africa/")
parquet_files = [blob.name for blob in blobs if blob.name.endswith('.parquet')]

print(f"Found {len(parquet_files)} parquet files")

# Check and fix each file
files_to_fix = []
files_fixed = []

for blob_name in tqdm(parquet_files, desc='Processing files', unit ='file'):
    try:
        # Read the file
        file_path = f"az://{container}/{blob_name}"
        df = pl.read_parquet(
            file_path,
            storage_options={'account_name': account_name},
            credential_provider=ResourceConfig.blob_credential_provider,
        )
        
        # Check if event_date is String
        if df.schema['event_date'] == pl.Utf8 or df.schema['event_date'] == pl.String:
            print(f"Found String event_date: {blob_name}")
            files_to_fix.append(blob_name)
            
            # Fix it: cast to Date
            df_fixed = df.with_columns([
                pl.col("event_date").str.strptime(pl.Date, "%Y-%m-%d", strict=False),
                pl.col("year").cast(pl.Int16, strict=False),
                pl.col("time_precision").cast(pl.Int16, strict=False),
                pl.col("iso").cast(pl.Int16, strict=False),
                pl.col("geo_precision").cast(pl.Int16, strict=False),
                pl.col("fatalities").cast(pl.Int16, strict=False),
                pl.col("latitude").cast(pl.Float64, strict=False),
                pl.col("longitude").cast(pl.Float64, strict=False),
                pl.col("timestamp").cast(pl.Int64).cast(pl.Datetime("ms"), strict=False),
                ])
            
            # Write back
            df_fixed.write_parquet(
                file_path,
                storage_options={'account_name': account_name},
                credential_provider=ResourceConfig.blob_credential_provider,
            )
            
            files_fixed.append(blob_name)
            print(f"  ✓ Fixed {blob_name}")
            
    except Exception as e:
        print(f"  ✗ Error processing {blob_name}: {e}")

print(f"\n{'='*60}")
print(f"Summary:")
print(f"  Total files scanned: {len(parquet_files)}")
print(f"  Files needing fix: {len(files_to_fix)}")
print(f"  Files fixed: {len(files_fixed)}")
print(f"{'='*60}")

if files_fixed:
    print("\nFixed files:")
    for f in files_fixed:
        print(f"  - {f}")

Scanning for parquet files...
Found 3591 parquet files

Processing files:  82%|████████▏ | 2928/3591 [49:36<10:35,  1.04file/s]

Found String event_date: daily_data/africa/event_date=2024-01-06/0.parquet

Processing files:  82%|████████▏ | 2929/3591 [49:38<13:42,  1.24s/file]

  ✓ Fixed daily_data/africa/event_date=2024-01-06/0.parquet

Processing files:  87%|████████▋ | 3119/3591 [52:49<07:50,  1.00file/s]

Found String event_date: daily_data/africa/event_date=2024-07-15/0.parquet

Processing files:  87%|████████▋ | 3120/3591 [52:51<09:25,  1.20s/file]

  ✓ Fixed daily_data/africa/event_date=2024-07-15/0.parquet

Processing files:  87%|████████▋ | 3135/3591 [53:03<06:07,  1.24file/s]

Found String event_date: daily_data/africa/event_date=2024-07-31/0.parquet

Processing files:  87%|████████▋ | 3136/3591 [53:05<08:07,  1.07s/file]

  ✓ Fixed daily_data/africa/event_date=2024-07-31/0.parquet

Processing files:  90%|████████▉ | 3219/3591 [54:29<08:36,  1.39s/file]

Found String event_date: daily_data/africa/event_date=2024-10-23/0.parquet

Processing files:  90%|████████▉ | 3220/3591 [54:31<09:09,  1.48s/file]

  ✓ Fixed daily_data/africa/event_date=2024-10-23/0.parquet

Processing files:  93%|█████████▎| 3329/3591 [56:18<03:47,  1.15file/s]

Found String event_date: daily_data/africa/event_date=2025-02-10/0.parquet

Processing files:  93%|█████████▎| 3330/3591 [56:20<05:02,  1.16s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-10/0.parquet
Found String event_date: daily_data/africa/event_date=2025-02-11/0.parquet

Processing files:  93%|█████████▎| 3331/3591 [56:22<05:46,  1.33s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-11/0.parquet
Found String event_date: daily_data/africa/event_date=2025-02-12/0.parquet

Processing files:  93%|█████████▎| 3332/3591 [56:24<06:11,  1.44s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-12/0.parquet
Found String event_date: daily_data/africa/event_date=2025-02-13/0.parquet

Processing files:  93%|█████████▎| 3333/3591 [56:25<06:28,  1.51s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-13/0.parquet
Found String event_date: daily_data/africa/event_date=2025-02-14/0.parquet

Processing files:  93%|█████████▎| 3334/3591 [56:27<06:51,  1.60s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-14/0.parquet
Found String event_date: daily_data/africa/event_date=2025-02-15/0.parquet

Processing files:  93%|█████████▎| 3335/3591 [56:29<07:03,  1.66s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-15/0.parquet
Found String event_date: daily_data/africa/event_date=2025-02-16/0.parquet

Processing files:  93%|█████████▎| 3336/3591 [56:31<07:04,  1.66s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-16/0.parquet

Processing files:  99%|█████████▉| 3555/3591 [1:00:05<00:37,  1.04s/file]

Found String event_date: daily_data/africa/event_date=2025-09-24/0.parquet

Processing files:  99%|█████████▉| 3556/3591 [1:00:07<00:43,  1.23s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-24/0.parquet

Processing files:  99%|█████████▉| 3558/3591 [1:00:08<00:33,  1.01s/file]

Found String event_date: daily_data/africa/event_date=2025-09-27/0.parquet

Processing files:  99%|█████████▉| 3559/3591 [1:00:10<00:38,  1.22s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-27/0.parquet
Found String event_date: daily_data/africa/event_date=2025-09-28/0.parquet

Processing files:  99%|█████████▉| 3560/3591 [1:00:12<00:42,  1.36s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-28/0.parquet
Found String event_date: daily_data/africa/event_date=2025-09-29/0.parquet

Processing files:  99%|█████████▉| 3561/3591 [1:00:14<00:43,  1.45s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-29/0.parquet
Found String event_date: daily_data/africa/event_date=2025-09-30/0.parquet

Processing files:  99%|█████████▉| 3562/3591 [1:00:15<00:43,  1.51s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-30/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-01/0.parquet

Processing files:  99%|█████████▉| 3563/3591 [1:00:17<00:43,  1.55s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-01/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-02/0.parquet

Processing files:  99%|█████████▉| 3564/3591 [1:00:19<00:44,  1.65s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-02/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-03/0.parquet

Processing files:  99%|█████████▉| 3565/3591 [1:00:20<00:43,  1.66s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-03/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-04/0.parquet

Processing files:  99%|█████████▉| 3566/3591 [1:00:22<00:41,  1.67s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-04/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-05/0.parquet

Processing files:  99%|█████████▉| 3567/3591 [1:00:25<00:46,  1.95s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-05/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-06/0.parquet

Processing files:  99%|█████████▉| 3568/3591 [1:00:28<00:57,  2.49s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-06/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-07/0.parquet

Processing files:  99%|█████████▉| 3569/3591 [1:00:30<00:49,  2.24s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-07/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-16/0.parquet

Processing files:  99%|█████████▉| 3570/3591 [1:00:32<00:43,  2.09s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-16/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-17/0.parquet

Processing files:  99%|█████████▉| 3571/3591 [1:00:34<00:40,  2.00s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-17/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-18/0.parquet

Processing files:  99%|█████████▉| 3572/3591 [1:00:35<00:36,  1.93s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-18/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-19/0.parquet

Processing files:  99%|█████████▉| 3573/3591 [1:00:37<00:34,  1.91s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-19/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-20/0.parquet

Processing files: 100%|█████████▉| 3574/3591 [1:00:39<00:32,  1.89s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-20/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-21/0.parquet

Processing files: 100%|█████████▉| 3575/3591 [1:00:41<00:29,  1.86s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-21/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-22/0.parquet

Processing files: 100%|█████████▉| 3576/3591 [1:00:43<00:27,  1.81s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-22/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-23/0.parquet

Processing files: 100%|█████████▉| 3577/3591 [1:00:44<00:25,  1.80s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-23/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-24/0.parquet

Processing files: 100%|█████████▉| 3578/3591 [1:00:46<00:23,  1.77s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-24/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-26/0.parquet

Processing files: 100%|█████████▉| 3579/3591 [1:00:48<00:21,  1.76s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-26/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-27/0.parquet

Processing files: 100%|█████████▉| 3580/3591 [1:00:52<00:26,  2.42s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-27/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-28/0.parquet

Processing files: 100%|█████████▉| 3581/3591 [1:00:55<00:25,  2.53s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-28/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-29/0.parquet

Processing files: 100%|█████████▉| 3582/3591 [1:00:56<00:20,  2.31s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-29/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-30/0.parquet

Processing files: 100%|█████████▉| 3583/3591 [1:00:58<00:17,  2.15s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-30/0.parquet
Found String event_date: daily_data/africa/event_date=2025-10-31/0.parquet

Processing files: 100%|█████████▉| 3584/3591 [1:01:00<00:13,  1.99s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-31/0.parquet
Found String event_date: daily_data/africa/event_date=2025-11-01/0.parquet

Processing files: 100%|█████████▉| 3585/3591 [1:01:01<00:11,  1.87s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-01/0.parquet
Found String event_date: daily_data/africa/event_date=2025-11-02/0.parquet

Processing files: 100%|█████████▉| 3586/3591 [1:01:03<00:09,  1.83s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-02/0.parquet
Found String event_date: daily_data/africa/event_date=2025-11-03/0.parquet

Processing files: 100%|█████████▉| 3587/3591 [1:01:05<00:07,  1.79s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-03/0.parquet
Found String event_date: daily_data/africa/event_date=2025-11-04/0.parquet

Processing files: 100%|█████████▉| 3588/3591 [1:01:06<00:05,  1.73s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-04/0.parquet
Found String event_date: daily_data/africa/event_date=2025-11-05/0.parquet

Processing files: 100%|█████████▉| 3589/3591 [1:01:08<00:03,  1.71s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-05/0.parquet
Found String event_date: daily_data/africa/event_date=2025-11-06/0.parquet

Processing files: 100%|█████████▉| 3590/3591 [1:01:10<00:01,  1.69s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-06/0.parquet
Found String event_date: daily_data/africa/event_date=2025-11-07/0.parquet

Processing files: 100%|██████████| 3591/3591 [1:01:11<00:00,  1.02s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-07/0.parquet

============================================================
Summary:
  Total files scanned: 3591
  Files needing fix: 45
  Files fixed: 45
============================================================

Fixed files:
  - daily_data/africa/event_date=2024-01-06/0.parquet
  - daily_data/africa/event_date=2024-07-15/0.parquet
  - daily_data/africa/event_date=2024-07-31/0.parquet
  - daily_data/africa/event_date=2024-10-23/0.parquet
  - daily_data/africa/event_date=2025-02-10/0.parquet
  - daily_data/africa/event_date=2025-02-11/0.parquet
  - daily_data/africa/event_date=2025-02-12/0.parquet
  - daily_data/africa/event_date=2025-02-13/0.parquet
  - daily_data/africa/event_date=2025-02-14/0.parquet
  - daily_data/africa/event_date=2025-02-15/0.parquet
  - daily_data/africa/event_date=2025-02-16/0.parquet
  - daily_data/africa/event_date=2025-09-24/0.parquet
  - daily_data/africa/event_date=2025-09-27/0.parquet
  - daily_data/africa/event_date=2025-09-28/0.parquet
  - daily_data/africa/event_date=2025-09-29/0.parquet
  - daily_data/africa/event_date=2025-09-30/0.parquet
  - daily_data/africa/event_date=2025-10-01/0.parquet
  - daily_data/africa/event_date=2025-10-02/0.parquet
  - daily_data/africa/event_date=2025-10-03/0.parquet
  - daily_data/africa/event_date=2025-10-04/0.parquet
  - daily_data/africa/event_date=2025-10-05/0.parquet
  - daily_data/africa/event_date=2025-10-06/0.parquet
  - daily_data/africa/event_date=2025-10-07/0.parquet
  - daily_data/africa/event_date=2025-10-16/0.parquet
  - daily_data/africa/event_date=2025-10-17/0.parquet
  - daily_data/africa/event_date=2025-10-18/0.parquet
  - daily_data/africa/event_date=2025-10-19/0.parquet
  - daily_data/africa/event_date=2025-10-20/0.parquet
  - daily_data/africa/event_date=2025-10-21/0.parquet
  - daily_data/africa/event_date=2025-10-22/0.parquet
  - daily_data/africa/event_date=2025-10-23/0.parquet
  - daily_data/africa/event_date=2025-10-24/0.parquet
  - daily_data/africa/event_date=2025-10-26/0.parquet
  - daily_data/africa/event_date=2025-10-27/0.parquet
  - daily_data/africa/event_date=2025-10-28/0.parquet
  - daily_data/africa/event_date=2025-10-29/0.parquet
  - daily_data/africa/event_date=2025-10-30/0.parquet
  - daily_data/africa/event_date=2025-10-31/0.parquet
  - daily_data/africa/event_date=2025-11-01/0.parquet
  - daily_data/africa/event_date=2025-11-02/0.parquet
  - daily_data/africa/event_date=2025-11-03/0.parquet
  - daily_data/africa/event_date=2025-11-04/0.parquet
  - daily_data/africa/event_date=2025-11-05/0.parquet
  - daily_data/africa/event_date=2025-11-06/0.parquet
  - daily_data/africa/event_date=2025-11-07/0.parquet

In [10]:
from dagster_acled.resources.resources import ResourceConfig
import polars as pl
from azure.storage.blob import ContainerClient
from pathlib import Path
from tqdm import tqdm


resource_dict = ResourceConfig.load_resource_config()
container = resource_dict['storage_account']['container']
account_name = resource_dict['storage_account']['name']

# Get blob service client
from azure.identity import DefaultAzureCredential
credential = DefaultAzureCredential()
container_client = ContainerClient(
    account_url=f"https://{account_name}.blob.core.windows.net",
    container_name=container,
    credential=credential
)

# Specific files to process
target_files = [
    "daily_data/africa/event_date=2024-01-06/0.parquet",
    "daily_data/africa/event_date=2024-07-15/0.parquet",
    "daily_data/africa/event_date=2024-07-31/0.parquet",
    "daily_data/africa/event_date=2024-10-23/0.parquet",
    "daily_data/africa/event_date=2025-02-10/0.parquet",
    "daily_data/africa/event_date=2025-02-11/0.parquet",
    "daily_data/africa/event_date=2025-02-12/0.parquet",
    "daily_data/africa/event_date=2025-02-13/0.parquet",
    "daily_data/africa/event_date=2025-02-14/0.parquet",
    "daily_data/africa/event_date=2025-02-15/0.parquet",
    "daily_data/africa/event_date=2025-02-16/0.parquet",
    "daily_data/africa/event_date=2025-09-24/0.parquet",
    "daily_data/africa/event_date=2025-09-27/0.parquet",
    "daily_data/africa/event_date=2025-09-28/0.parquet",
    "daily_data/africa/event_date=2025-09-29/0.parquet",
    "daily_data/africa/event_date=2025-09-30/0.parquet",
    "daily_data/africa/event_date=2025-10-01/0.parquet",
    "daily_data/africa/event_date=2025-10-02/0.parquet",
    "daily_data/africa/event_date=2025-10-03/0.parquet",
    "daily_data/africa/event_date=2025-10-04/0.parquet",
    "daily_data/africa/event_date=2025-10-05/0.parquet",
    "daily_data/africa/event_date=2025-10-06/0.parquet",
    "daily_data/africa/event_date=2025-10-07/0.parquet",
    "daily_data/africa/event_date=2025-10-16/0.parquet",
    "daily_data/africa/event_date=2025-10-17/0.parquet",
    "daily_data/africa/event_date=2025-10-18/0.parquet",
    "daily_data/africa/event_date=2025-10-19/0.parquet",
    "daily_data/africa/event_date=2025-10-20/0.parquet",
    "daily_data/africa/event_date=2025-10-21/0.parquet",
    "daily_data/africa/event_date=2025-10-22/0.parquet",
    "daily_data/africa/event_date=2025-10-23/0.parquet",
    "daily_data/africa/event_date=2025-10-24/0.parquet",
    "daily_data/africa/event_date=2025-10-26/0.parquet",
    "daily_data/africa/event_date=2025-10-27/0.parquet",
    "daily_data/africa/event_date=2025-10-28/0.parquet",
    "daily_data/africa/event_date=2025-10-29/0.parquet",
    "daily_data/africa/event_date=2025-10-30/0.parquet",
    "daily_data/africa/event_date=2025-10-31/0.parquet",
    "daily_data/africa/event_date=2025-11-01/0.parquet",
    "daily_data/africa/event_date=2025-11-02/0.parquet",
    "daily_data/africa/event_date=2025-11-03/0.parquet",
    "daily_data/africa/event_date=2025-11-04/0.parquet",
    "daily_data/africa/event_date=2025-11-05/0.parquet",
    "daily_data/africa/event_date=2025-11-06/0.parquet",
    "daily_data/africa/event_date=2025-11-07/0.parquet",
]

print(f"Processing {len(target_files)} specific files")

# Check and fix each file
files_fixed = []
files_errored = []

for blob_name in tqdm(target_files, desc='Processing files', unit='file'):
    try:
        # Read the file
        file_path = f"az://{container}/{blob_name}"
        df = pl.read_parquet(
            file_path,
            storage_options={'account_name': account_name},
            credential_provider=ResourceConfig.blob_credential_provider,
        )
        
        # Build schema enforcement with proper handling
        cast_expressions = []
        
        # Handle event_date - convert String to Date
        if df.schema['event_date'] in (pl.Utf8, pl.String):
            cast_expressions.append(
                pl.col("event_date").str.strptime(pl.Date, "%Y-%m-%d", strict=False)
            )
        elif df.schema['event_date'] != pl.Date:
            cast_expressions.append(pl.col("event_date").cast(pl.Date, strict=False))
        
        # Enforce integer types
        if 'year' in df.columns:
            cast_expressions.append(pl.col("year").cast(pl.Int16, strict=False))
        if 'time_precision' in df.columns:
            cast_expressions.append(pl.col("time_precision").cast(pl.Int16, strict=False))
        if 'iso' in df.columns:
            cast_expressions.append(pl.col("iso").cast(pl.Int16, strict=False))
        if 'geo_precision' in df.columns:
            cast_expressions.append(pl.col("geo_precision").cast(pl.Int16, strict=False))
        if 'fatalities' in df.columns:
            cast_expressions.append(pl.col("fatalities").cast(pl.Int16, strict=False))
        
        # Enforce float types
        if 'latitude' in df.columns:
            cast_expressions.append(pl.col("latitude").cast(pl.Float64, strict=False))
        if 'longitude' in df.columns:
            cast_expressions.append(pl.col("longitude").cast(pl.Float64, strict=False))
        
        # Handle timestamp - convert to datetime if it's Int64
        if 'timestamp' in df.columns:
            if df.schema['timestamp'] == pl.Int64:
                cast_expressions.append(
                    pl.col("timestamp").cast(pl.Datetime("ms"), strict=False)
                )
            elif df.schema['timestamp'] != pl.Datetime("ms"):
                cast_expressions.append(
                    pl.col("timestamp").cast(pl.Datetime("ms"), strict=False)
                )
        
        # Apply all casts if needed
        if cast_expressions:
            df_fixed = df.with_columns(cast_expressions)
            
            # Write back
            df_fixed.write_parquet(
                file_path,
                storage_options={'account_name': account_name},
                credential_provider=ResourceConfig.blob_credential_provider,
            )
            
            files_fixed.append(blob_name)
            print(f"  ✓ Fixed {blob_name}")
        else:
            print(f"  → No changes needed for {blob_name}")
            
    except Exception as e:
        print(f"  ✗ Error processing {blob_name}: {e}")
        files_errored.append((blob_name, str(e)))

print(f"\n{'='*60}")
print(f"Summary:")
print(f"  Total files processed: {len(target_files)}")
print(f"  Files fixed: {len(files_fixed)}")
print(f"  Files with errors: {len(files_errored)}")
print(f"{'='*60}")

if files_fixed:
    print("\nFixed files:")
    for f in files_fixed:
        print(f"  - {f}")

if files_errored:
    print("\nFiles with errors:")
    for f, err in files_errored:
        print(f"  - {f}: {err}")

Processing 45 specific files

Processing files:   2%|▏         | 1/45 [00:03<02:49,  3.85s/file]

  ✓ Fixed daily_data/africa/event_date=2024-01-06/0.parquet

Processing files:   4%|▍         | 2/45 [00:06<02:16,  3.17s/file]

  ✓ Fixed daily_data/africa/event_date=2024-07-15/0.parquet

Processing files:   7%|▋         | 3/45 [00:09<02:06,  3.01s/file]

  ✓ Fixed daily_data/africa/event_date=2024-07-31/0.parquet

Processing files:   9%|▉         | 4/45 [00:10<01:41,  2.47s/file]

  ✓ Fixed daily_data/africa/event_date=2024-10-23/0.parquet

Processing files:  11%|█         | 5/45 [00:12<01:26,  2.15s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-10/0.parquet

Processing files:  13%|█▎        | 6/45 [00:14<01:16,  1.97s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-11/0.parquet

Processing files:  16%|█▌        | 7/45 [00:15<01:12,  1.90s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-12/0.parquet

Processing files:  18%|█▊        | 8/45 [00:18<01:22,  2.23s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-13/0.parquet

Processing files:  20%|██        | 9/45 [00:20<01:13,  2.04s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-14/0.parquet

Processing files:  22%|██▏       | 10/45 [00:22<01:06,  1.91s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-15/0.parquet

Processing files:  24%|██▍       | 11/45 [00:23<01:01,  1.81s/file]

  ✓ Fixed daily_data/africa/event_date=2025-02-16/0.parquet

Processing files:  27%|██▋       | 12/45 [00:26<01:08,  2.09s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-24/0.parquet

Processing files:  29%|██▉       | 13/45 [00:30<01:21,  2.56s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-27/0.parquet

Processing files:  31%|███       | 14/45 [00:32<01:21,  2.62s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-28/0.parquet

Processing files:  33%|███▎      | 15/45 [00:34<01:09,  2.32s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-29/0.parquet

Processing files:  36%|███▌      | 16/45 [00:36<01:01,  2.11s/file]

  ✓ Fixed daily_data/africa/event_date=2025-09-30/0.parquet

Processing files:  38%|███▊      | 17/45 [00:37<00:55,  2.00s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-01/0.parquet

Processing files:  40%|████      | 18/45 [00:39<00:51,  1.92s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-02/0.parquet

Processing files:  42%|████▏     | 19/45 [00:41<00:47,  1.84s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-03/0.parquet

Processing files:  44%|████▍     | 20/45 [00:42<00:44,  1.79s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-04/0.parquet

Processing files:  47%|████▋     | 21/45 [00:44<00:41,  1.73s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-05/0.parquet

Processing files:  49%|████▉     | 22/45 [00:46<00:39,  1.72s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-06/0.parquet

Processing files:  51%|█████     | 23/45 [00:48<00:39,  1.79s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-07/0.parquet

Processing files:  53%|█████▎    | 24/45 [00:49<00:36,  1.75s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-16/0.parquet

Processing files:  56%|█████▌    | 25/45 [00:52<00:40,  2.00s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-17/0.parquet

Processing files:  58%|█████▊    | 26/45 [00:56<00:49,  2.59s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-18/0.parquet

Processing files:  60%|██████    | 27/45 [00:58<00:42,  2.38s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-19/0.parquet

Processing files:  62%|██████▏   | 28/45 [01:00<00:38,  2.27s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-20/0.parquet

Processing files:  64%|██████▍   | 29/45 [01:01<00:33,  2.10s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-21/0.parquet

Processing files:  67%|██████▋   | 30/45 [01:03<00:29,  1.97s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-22/0.parquet

Processing files:  69%|██████▉   | 31/45 [01:05<00:26,  1.92s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-23/0.parquet

Processing files:  71%|███████   | 32/45 [01:07<00:24,  1.85s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-24/0.parquet

Processing files:  73%|███████▎  | 33/45 [01:08<00:21,  1.79s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-26/0.parquet

Processing files:  76%|███████▌  | 34/45 [01:10<00:19,  1.80s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-27/0.parquet

Processing files:  78%|███████▊  | 35/45 [01:12<00:18,  1.83s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-28/0.parquet

Processing files:  80%|████████  | 36/45 [01:14<00:16,  1.81s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-29/0.parquet

Processing files:  82%|████████▏ | 37/45 [01:15<00:14,  1.78s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-30/0.parquet

Processing files:  84%|████████▍ | 38/45 [01:18<00:14,  2.12s/file]

  ✓ Fixed daily_data/africa/event_date=2025-10-31/0.parquet

Processing files:  87%|████████▋ | 39/45 [01:22<00:15,  2.61s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-01/0.parquet

Processing files:  89%|████████▉ | 40/45 [01:24<00:11,  2.31s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-02/0.parquet

Processing files:  91%|█████████ | 41/45 [01:26<00:08,  2.15s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-03/0.parquet

Processing files:  93%|█████████▎| 42/45 [01:27<00:05,  2.00s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-04/0.parquet

Processing files:  96%|█████████▌| 43/45 [01:29<00:03,  1.88s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-05/0.parquet

Processing files:  98%|█████████▊| 44/45 [01:31<00:01,  1.91s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-06/0.parquet

Processing files: 100%|██████████| 45/45 [01:33<00:00,  2.07s/file]

  ✓ Fixed daily_data/africa/event_date=2025-11-07/0.parquet

============================================================
Summary:
  Total files processed: 45
  Files fixed: 45
  Files with errors: 0
============================================================

Fixed files:
  - daily_data/africa/event_date=2024-01-06/0.parquet
  - daily_data/africa/event_date=2024-07-15/0.parquet
  - daily_data/africa/event_date=2024-07-31/0.parquet
  - daily_data/africa/event_date=2024-10-23/0.parquet
  - daily_data/africa/event_date=2025-02-10/0.parquet
  - daily_data/africa/event_date=2025-02-11/0.parquet
  - daily_data/africa/event_date=2025-02-12/0.parquet
  - daily_data/africa/event_date=2025-02-13/0.parquet
  - daily_data/africa/event_date=2025-02-14/0.parquet
  - daily_data/africa/event_date=2025-02-15/0.parquet
  - daily_data/africa/event_date=2025-02-16/0.parquet
  - daily_data/africa/event_date=2025-09-24/0.parquet
  - daily_data/africa/event_date=2025-09-27/0.parquet
  - daily_data/africa/event_date=2025-09-28/0.parquet
  - daily_data/africa/event_date=2025-09-29/0.parquet
  - daily_data/africa/event_date=2025-09-30/0.parquet
  - daily_data/africa/event_date=2025-10-01/0.parquet
  - daily_data/africa/event_date=2025-10-02/0.parquet
  - daily_data/africa/event_date=2025-10-03/0.parquet
  - daily_data/africa/event_date=2025-10-04/0.parquet
  - daily_data/africa/event_date=2025-10-05/0.parquet
  - daily_data/africa/event_date=2025-10-06/0.parquet
  - daily_data/africa/event_date=2025-10-07/0.parquet
  - daily_data/africa/event_date=2025-10-16/0.parquet
  - daily_data/africa/event_date=2025-10-17/0.parquet
  - daily_data/africa/event_date=2025-10-18/0.parquet
  - daily_data/africa/event_date=2025-10-19/0.parquet
  - daily_data/africa/event_date=2025-10-20/0.parquet
  - daily_data/africa/event_date=2025-10-21/0.parquet
  - daily_data/africa/event_date=2025-10-22/0.parquet
  - daily_data/africa/event_date=2025-10-23/0.parquet
  - daily_data/africa/event_date=2025-10-24/0.parquet
  - daily_data/africa/event_date=2025-10-26/0.parquet
  - daily_data/africa/event_date=2025-10-27/0.parquet
  - daily_data/africa/event_date=2025-10-28/0.parquet
  - daily_data/africa/event_date=2025-10-29/0.parquet
  - daily_data/africa/event_date=2025-10-30/0.parquet
  - daily_data/africa/event_date=2025-10-31/0.parquet
  - daily_data/africa/event_date=2025-11-01/0.parquet
  - daily_data/africa/event_date=2025-11-02/0.parquet
  - daily_data/africa/event_date=2025-11-03/0.parquet
  - daily_data/africa/event_date=2025-11-04/0.parquet
  - daily_data/africa/event_date=2025-11-05/0.parquet
  - daily_data/africa/event_date=2025-11-06/0.parquet
  - daily_data/africa/event_date=2025-11-07/0.parquet

In [ ]:
import polars as pl


result = (
    pl.scan_parquet("s3://dagster-acled-bucket/acled/acled_daily_data/acled_africa/*")
    .select([pl.exclude("tags")])
    .sort("event_type")
    .collect(engine="streaming")
    .limit(n = 100)
)

In [7]:
result.select('event_date').max()

shape: (1, 1)
┌────────────┐
│ event_date │
│ ---        │
│ date       │
╞════════════╡
│ 2016-01-08 │
└────────────┘

In [1]:
import yaml
import polars as pl
from azure.identity import DefaultAzureCredential

with open('/Users/stefanbozhilov/repos/acled/acled/dagster_pipeline/dagster_acled/resources/resource_config.yaml', 'r') as file:
    config = yaml.safe_load(file)

credential = DefaultAzureCredential()
token = credential.get_token("https://storage.azure.com/.default")

# Correct parameter name and format
storage_options = {
    "account_name": config['storage_account']['name'],
    "bearer_token": token.token
}

# result.write_parquet(
#     file=f"az://{config['storage_account']['container']}/daily_data/africa",
#     storage_options=storage_options,  # Changed from credential_provider
#     partition_by=['event_date']
# )

In [24]:
import os
from dagster import Definitions, asset, EnvVar
from dagster_azure.blob import (
    AzureBlobStorageResource,
    AzureBlobStorageKeyCredential,
    AzureBlobStorageDefaultCredential
)

@asset
def my_table(azure_blob_storage: AzureBlobStorageResource):
    with azure_blob_storage.get_client() as blob_storage_client:
        response = blob_storage_client.list_containers()

definitions = Definitions(
    assets=[my_table],
    resources={
        "azure_blob_storage": AzureBlobStorageResource(
            account_url=config['storage_account']['url'],
            credential = AzureBlobStorageDefaultCredential()
        ),
    },
)

In [ ]:
import os

from dagster import (
    Definitions,
    load_asset_checks_from_modules,
    load_assets_from_modules,
    multiprocess_executor,
)
from dotenv import load_dotenv

from dagster_acled.asset_checks import acled_checks
from dagster_acled.assets import base_assets, ml, report, country_assets
from dagster_acled.jobs import acled_update_job
from dagster_acled.utils import load_config
from dagster_acled.resources.io_manager import (
    reports_s3_io_manager,
    s3_io_manager,
    s3_pickle_io_manager,
)
from dagster_acled.resources.resources import ResourceConfig
from dagster_acled.schedules import daily_schedule
from dagster_acled.secrets_config import SecretManager
from dagster_acled.sensors import acled_sensor, s3_data_availability_sensor
from dagster_azure.blob import (
    AzureBlobStorageResource,
    AzureBlobStorageDefaultCredential
)

load_dotenv()

sm = SecretManager(region_name=os.environ['REGION_NAME'])
resource_config = ResourceConfig.from_secrets(sm=sm, s3_secret_name="acled_bucket", pg_secret_name="acled_postgres")
resource_yaml = load_config(config_path="dagster_pipeline/dagster_acled/resources/resource_config.yaml")

resources = {
    "s3": resource_config.s3,
    "postgres": resource_config.postgres,
    "s3_io_manager": s3_io_manager,
    "reports_s3_io_manager": reports_s3_io_manager,
    "s3_pickle_io_manager": s3_pickle_io_manager,
    "azure_blob_storage": AzureBlobStorageResource(
            account_url=(resource_yaml['storage_account']['url']),
            credential=AzureBlobStorageDefaultCredential()
    )
}

FileNotFoundError: [Errno 2] No such file or directory: 'dagster_acled/resources/resource_config.yaml'

In [9]:
from dagster_acled.secrets_config import *

In [1]:
from dagster_acled.acled_request_config import * 
from dagster_acled.secrets_config import *
import yaml

with open('/Users/stefanbozhilov/repos/acled/acled/dagster_pipeline/dagster_acled/resources/resource_config.yaml', 'r') as file:
    config = yaml.safe_load(file)

sm = SecretManager(vault_url = config['keyvault']['url'], 
                   region_name=None)   

cred = sm.get_secret(secret_name='acled-credentials', 
                     source = 'az')

username = cred['username']
password = cred['password']

/Users/stefanbozhilov/repos/acled/acled/dagster_pipeline/.venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:198: UserWarning: Field name "schema" in "PostgreSQLResource" shadows an attribute in parent "ConfigurableResource"
  warnings.warn(